security:
    firewalls:
        main:
            lazy: true
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    password_hashers:
        App\Entity\User:
            algorithm: auto
